baseURL: https://www.clouddatascience.org/
languageCode: en-us
title: Cloud-Based Data Science
theme: hugo-fresh

params:
  navbarlogo:
  # Logo (from /images/logos/___)
   image: logos/logo_new_black.png
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Cloud-Based Data Science
    # Hero subtitle (optional)
    subtitle: Cloud-Based Data Science (CBDS) consists of two parts. One, a set of pay-what-you-want (including free!) massive open online courses that can be completed on any computer with a web browser and an internet connection. 
    subtitle2: Two, Cloud-Based Data Science Plus (CBDS+) is a no-cost, paid 14-week educational initiative for young-adult, high school and GED-graduates in Baltimore City. Offered by the Johns Hopkins Bloomberg School of Public Health, in partnership with the Historic East Baltimore Community Action Coalition and Leanpub, CBDS+ aims to equip members of surrounding communities with the necessary skills and support required to work in the booming field of data science.
    subtitle3: We aim to equip individuals from underserved populations with the necessary skills and support required to work in the field of data science. A portion of anything you pay for the online courses supports the CBDS+ program.
    #subtitle4: 
    # Button text
    buttontext: Take our courses today!
    # Where the main hero button links to
    buttonlink: "https://leanpub.com/universities/set/jhu/cloud-based-data-science"
    # Hero image (from /images/___)
    image: illustrations/worker.svg
    # Footer logos (from /images/logos/clients/___.svg)
    clientlogos:
    - hebcac.png
    - rstudio.png
    - leanpub.png
    - pforward.png 
    - starbucks.png
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  #- title: About
  #  url: /about.html/
  - title: For Employers
    url: /foremployers.html/
  - title: For Learners
    url: /forlearners.html/
  - title: For Educators
    url: /foreducators.html/
  - title: Contact
    url: /contact.html/
  - title: Our Team
    url: /team.html/
    #sublinks:
    #- title: Dropdown item
    #  url: /
    #- title: Dropdown item
    #  url: /
    #- title: Dropdown item
    #  url: /
  - title: Donate
    url: /donate.html/
    button: true
  #sidebar:
    # Logo (from /images/logos/___.svg)
  #  logo: fresh-square
  #  sections:
  #  - title: User
  #    icon: user
  #    links:
  #    - text: Profile
  #      url: /
  #    - text: Account
  #      url: /
  #    - text: Settings
  #      url: /
  #  - title: Messages
  #    icon: envelope
  #    links:
  #    - text: Inbox
  #      url: /
  #    - text: Compose
  #      url: /
  #  - title: Images
  #    icon: image
  #    links:
  #    - text: Library
  #      url: /
  #    - text: Upload
  #      url: /
  #  - title: Settings
  #    icon: cog
  #    links:
  #    - text: User settings
  #      url: /
  #    - text: App settings
  #      url: /
  section2:
    title: Our Approach
    subtitle:  
    features:
    - title: We minimize computer costs
      text: We have developed an online program that lets students do data science using only a web browser and inexpensive computers like Chromebooks.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop2.png
      buttonText: Learn more about Google Chromebook
      url: https://www.google.com/chromebook/
    - title: Free Courses
      text: Our CBDS program is entirely online and you can take it for free. You can take the classes any time and at your own pace. You get a certificate for each CBDS online class from Leanpub.
      icon: diploma2.png
      buttonText: See our curriculum
      url: https://leanpub.com/universities/set/jhu/cloud-based-data-science
    - title: Learn anywhere
      text: Data science work can be done from anywhere there is an Internet connection and so can the CBDS program.
      icon: remote2.png
      buttonText: Why online courses
      url: /
    - title: Finding Jobs
      text: Our program covers soft skills you need to get data science jobs, including how to network and get your name out there. We are also interested in working with partner companies who need to fill data science roles to place our graduates in remote and local data science jobs. (If you are looking for data scientists consider becoming a CBDS hiring partner).
      icon: network3.png
      buttonText: Hear our success stories
      url: /
  section3:
    title: Our Curriculum
    subtitle: Our 11 courses cover topics such as Google and the Cloud, Organizing Data Science Projects, Version Control, R, Data Tidying, Data Viz, Data Analysis, Written and Oral Communication in Data Science, and Getting a Job in Data Science
    image: illustrations/mockups/logo-01.png
    buttonText: See our curriculum on Leanpub!
    buttonLink: "https://leanpub.com/universities/set/jhu/cloud-based-data-science"
  section4:
    title: Our Team
    subtitle: 
    clients:
    - name: Jeff Leek
      quote: Jeff Leek is the Director of the CBDS+ program. He is also a professor of biostatistics and the co-director of the Data Science Lab at Johns Hopkins University Bloomberg School of Public Health. 
      job: 
      img: jeff.png
    - name: Ashley Johnson
      quote: Ashley K.G. Johnson is the Program Administrator for CBDS+. She facilitates tutoring for program participants and manages both recruitment efforts and the development of corporate and non-profit partnerships.
      job: 
      img: ashley.png
    - name: Aboozar Hadavand
      quote: Aboozar Hadavand is the Curriculum Lead for CBDS. He is also a postdoctoral fellow at Johns Hopkins Bloomberg School of Public Health. He has previously taught at Barnard College and Brooklyn College.
      job: 
      img: aboozar.jpg 
    clients2:
    - name2: Shannon Ellis
      quote2: Shannon Ellis is the Curriculum Lead and part of our Technology Development team at CBDS. She is an Assistant Teaching Professor of Cognitive Sciences at the University of California, San Diego.
      job2: 
      img2: shannon.png
    - name2: Simone Sawyer
      quote2: Simone Sawyer is the Scholar Advocate for CBDS+. She serves as a case manager and professional development coach for current and alumni scholars. By ensuring scholars are connected to wrap-around services and work-place tips, it is the hope that they will succeed both personally and professionally in the data science field.
      job2: 
      img2: simone.png
    - name2: Sean Kross
      quote2: Sean Kross is part of our Technology Development team at CBDS and is a PhD student in Cognitive Sciences at the University of California, San Diego.
      job2: 
      img2: sean.jpeg
    clients3:
    - name3: John Muschelli
      quote3: John Muschelli leads our Technology Development team. He is an Assistant Scientist at the Department of Biostatistics at Johns Hopkins University.
      job3: 
      img3: john.jpeg

    # Logo (from /images/logos/___)
    logo: logo_new_white.png
    # Social media links (GitHub, Twitter, etc.). All are optional.
    #socialmedia:
    #- link: https://github.com/lucperkins/github-fresh
      # Icons are from Font Awesome
      #icon: github
    #- link: https://facebook.com/#
    #  icon: facebook
    #- link: https://twitter.com/lucperkins
    #  icon: twitter
    bulmalogo: false
    quicklinks:
      column1:
        title: 
        links: 
        - text: For Employers
          link: /foremployers.html/
        - text: Our Team
          link: /team.html/
      column2:
        title: 
        links:
        - text: For Learners
          link: /forlearners.html/
        - text: Contact us
          link: /contact.html/
      column3:
        title: 
        links:
        - text: For Educators
          link: /foreducators.html/
        - text: Donate
          link: /donate.html/
